language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install --user --upgrade -r requirements.txt
  - pip install --user pytest-cov
  - pip install --user coveralls

install:
  - pip install .

script:
  - pytest --cov=./ yase

after_success:
  - coveralls
