language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install autograd
  - pip install matplotlib
  - pip install numpy
  - pip install pytest-cov
  - pip install qpsolvers
  - pip install scikit-learn
  - pip install scipy

script:
  - pytest --cov=./
