language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install autograd
  - pip install matplotlib
  - pip install numpy
  - pip install pytest

script:
  - py.test --cov=./

notifications:
  email: false
