language: python

python:
  - 3.6
  - 3.7

install:
  - pip install autograd
  - pip install cvxopt
  - pip install cvxpy
  - pip install matplotlib
  - pip install --upgrade numpy
  - pip install osqp
  - pip install pytest-cov
  - pip install qpsolvers
  - pip install scikit-learn
  - pip install scipy

script:
  - pytest --cov=./
