language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip -m install --upgrade -r requirements.txt
  - pip -m install pytest-cov
  - pip -m install coveralls

install:
  - pip install .

script:
  - pytest --cov=./ yase

after_success:
  - coveralls
