language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install -m --upgrade -r requirements.txt
  - pip install -m pytest-cov
  - pip install -m coveralls

install:
  - pip install .

script:
  - pytest --cov=./ yase

after_success:
  - coveralls
