language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - pip install pytest-cov
  - pip install coveralls

install:
  - pip install --upgrade -r requirements.txt
  - pip install .

script:
  - pytest --cov=./ optiml

after_success:
  - coveralls
